---
repos:
  # - repo: https://github.com/pre-commit/mirrors-yapf
  #   rev: 'v0.32.0'  # Use the sha / tag you want to point at
  #   hooks:
  #     - id: yapf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/pre-commit/mirrors-pylint
  #  rev: v2.4.4
  #  hooks:
  #    - id: pylint
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.3.5'
    hooks:
    - id: ruff
      args: [--fix]
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
