---
language: python

python:
 - "3.8"
 - "3.9"

git:
 submodules: false

before_install:
 - sudo apt-get update && sudo apt-get install -y libcap-dev

install:
 - pip3 install git+https://github.com/prusa3d/Prusa-Connect-SDK-Printer.git@master#egg=prusa.connect.sdk.printer
 - pip3 install -U -r requirements.txt
 - pip3 install -U types-pkg_resources
 - pip3 install -U pytest pytest-pylint pytest-doctestplus pytest-mypy mock

script:
  - PYTHONPATH=`pwd` pytest -v --mypy --pylint --doctest-plus --doctest-rst

before_deploy:
 - python3 setup.py sdist
 - python3 setup.py bdist_wheel
