CONNECT_CONFIG_PATH = "/boot/lan_settings.ini"
PRINTER_PORT = "/dev/ttyAMA0"
PRINTER_BAUDRATE = 115200

PRINTER_RESPONSE_TIMEOUT = 1
LONG_GCODE_TIMEOUT = 120
REPEAT_ACTION_EVERY = 10
COMMAND_TIMEOUT = 600
SD_LIST_TIMEOUT = 5

TELEMETRY_INTERVAL = 1
STATUS_UPDATE_INTERVAL_SEC = 2
QUIT_INTERVAL = 0.2
SD_INTERVAL = 4
SHOW_IP_INTERVAL = 60

OLD_BUDDY_LOG_LEVEL = "DEBUG"
SERIAL_LOG_LEVEL = "DEBUG"
CONNECT_API_LOG_LEVEL = "DEBUG"
STATE_MANAGER_LOG_LEVEL = "DEBUG"
COMMANDS_LOG_LEVEL = "DEBUG"
LCD_PRINTER_LOG_LEVEL = "DEBUG"
SD_CARD_LOG_LEVEL = "DEBUG"
