CONNECT_CONFIG_PATH = "/boot/lan_settings.ini"
PRINTER_PORT = "/dev/ttyAMA0"
PRINTER_BAUDRATE = 115200

PRINTER_RESPONSE_TIMEOUT = 1
LONG_GCODE_TIMEOUT = 120
TRY_STOPPING_EVERY = 10

TELEMETRY_INTERVAL = 1
STATUS_UPDATE_INTERVAL_SEC = 2
QUIT_INTERVAL = 0.2