CONNECT_CONFIG_PATH = "/boot/lan_settings.ini"
PRINTER_PORT = "/dev/ttyAMA0"
PRINTER_BAUDRATE = 115200
RX_SIZE = 128

# Time is in seconds

PRINTER_RESPONSE_TIMEOUT = 1
LOAD_FILE_TIMEOUT = 5
GCODE_RETRIES_TIMEOUT = 10
LONG_GCODE_TIMEOUT = 120
COMMAND_TIMEOUT = 600
SD_LIST_TIMEOUT = 5
PRINTER_INFO_TIMEOUT = 10

TELEMETRY_INTERVAL = 1
STATUS_UPDATE_INTERVAL = 2
QUIT_INTERVAL = 0.2
SD_INTERVAL = 4
SHOW_IP_INTERVAL = 60
ACTION_INTERVAL = 10

LCD_QUEUE_SIZE = 20

SERIAL_QUEUE_TIMEOUT = 10
SERIAL_QUEUE_MONITOR_INTERVAL = 1

OLD_BUDDY_LOG_LEVEL = "DEBUG"
SERIAL_LOG_LEVEL = "DEBUG"
CONNECT_API_LOG_LEVEL = "DEBUG"
STATE_MANAGER_LOG_LEVEL = "DEBUG"
COMMANDS_LOG_LEVEL = "DEBUG"
LCD_PRINTER_LOG_LEVEL = "DEBUG"
SD_CARD_LOG_LEVEL = "DEBUG"
IP_UPDATER_LOG_LEVEL = "DEBUG"
TELEMETRY_GATHERER_LOG_LEVEL = "DEBUG"
INFO_SENDER_LOG_LEVEL = "DEBUG"
SERIAL_QUEUE_LOG_LEVEL = "DEBUG"
